spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/techpost_dev
    username: postgres # TODO: change username and password for local setup
    password: postgres # TODO: change username and password for local setup
