server:
  port: 18020

spring:
  application:
    name: 'app-batch'

  batch:
    jdbc:
      initialize-schema: always
      # table-prefix: BATCH_
      # isolation-level-for-create: serializable

scheduler:
  cron:
    post-scrap: "0 0 7 * * *"
